CLASS zcl_sectors_get DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
    METHODS: get_sectors RETURNING VALUE(rt_data) TYPE ztttspat.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_SECTORS_GET IMPLEMENTATION.


  METHOD get_sectors.

    "SELECT * FROM tspat INTO TABLE @rt_data.
    CALL FUNCTION 'YFMSD_SECTORS_GET' DESTINATION 'RFC_DS4'
    TABLES
      ET_SECTORS = rt_data.
  ENDMETHOD.
ENDCLASS.
