FUNCTION-POOL ZHFIS_DETIVA.                 "MESSAGE-ID ..

TYPES: BEGIN OF ty_bsakbsad,
         bukrs TYPE bukrs,
         belnr TYPE belnr_d,
         gjahr TYPE gjahr,
         buzei TYPE buzei,
         budat TYPE budat,
         bldat TYPE bldat,
         cpudt TYPE datum,
         xblnr TYPE xblnr,
         augbl TYPE augbl,
         auggj TYPE gjahr,
         waers TYPE waers,
         shkzg TYPE shkzg,
         dmbtr TYPE dmbtr,
         wrbtr TYPE wrbtr,
         lifnr TYPE lifnr,
         kunnr TYPE kunnr,
         blart TYPE blart,
       END OF ty_bsakbsad,

       BEGIN OF ty_listadoccompprov,
         bukrs TYPE bukrs,
         augbl TYPE augbl,
         auggj TYPE gjahr,
         belnr TYPE belnr_d,
         gjahr TYPE gjahr,
       END OF ty_listadoccompprov,

       BEGIN OF ty_listadoccompcli,
         bukrs TYPE bukrs,
         augbl TYPE augbl,
         auggj TYPE gjahr,
         belnr TYPE belnr_d,
         gjahr TYPE gjahr,
       END OF ty_listadoccompcli,

       BEGIN OF ty_bseg,
         bukrs TYPE bukrs,
         belnr TYPE belnr_d,
         gjahr TYPE gjahr,
         buzei TYPE buzei,
         koart TYPE koart,
         shkzg TYPE zst_bseg-shkzg,
         dmbtr TYPE zst_bseg-dmbtr,
         wrbtr TYPE zst_bseg-wrbtr,
         mwskz TYPE zst_bseg-mwskz,
         hkont TYPE zst_bseg-hkont,
       END OF ty_bseg,

       BEGIN OF ty_listadoc_fi,
         bukrs TYPE bukrs,
         belnr TYPE belnr_d,
         gjahr TYPE gjahr,
       END OF ty_listadoc_fi,

       BEGIN OF ty_bkpf_fi,
         bukrs TYPE bukrs,
         belnr TYPE belnr_d,
         gjahr TYPE gjahr,
         bktxt TYPE bktxt,
         usnam TYPE usnam,
       END OF ty_bkpf_fi,

       BEGIN OF ty_bkpf_tc_pago,
         bukrs TYPE bukrs,
         belnr TYPE belnr_d,
         gjahr TYPE gjahr,
         kursf TYPE zkursf,
         blart TYPE blart,
         bldat TYPE bldat,
       END OF ty_bkpf_tc_pago,

       BEGIN OF ty_lifnr,
         lifnr TYPE lifnr,
       END OF ty_lifnr,

       BEGIN OF ty_kunnr,
         kunnr TYPE kunnr,
       END OF ty_kunnr.


DATA: lt_bsakbsad          TYPE TABLE OF ty_bsakbsad,
      ls_bsakbsad          TYPE ty_bsakbsad,
      lt_listadoccompprov  TYPE TABLE OF ty_listadoccompprov,
      ls_listadoccompprov  TYPE ty_listadoccompprov,
      lt_listadoccompcli   TYPE TABLE OF ty_listadoccompcli,
      ls_listadoccompcli   TYPE ty_listadoccompcli,
      lt_docsdetiva        TYPE ztt_zhfis_detiva,
      ls_docsdetiva        TYPE zst_zhfis_detiva,
      lt_bseg              TYPE TABLE OF ty_bseg,
      ls_bseg              TYPE ty_bseg,
      lt_bseg_temp         TYPE TABLE OF ty_bseg,
      ls_bseg_temp         TYPE ty_bseg,
      lt_listadoc          TYPE TABLE OF ty_listadoccompprov,
      ls_listadoc          TYPE ty_listadoccompprov,
      lt_listadoc_fi       TYPE TABLE OF ty_listadoc_fi,
      ls_listadoc_fi       TYPE ty_listadoc_fi,
      lt_bkpf_fi           TYPE TABLE OF ty_bkpf_fi,
      ls_bkpf_fi           TYPE ty_bkpf_fi,
      lt_bkpf_tc_pago      TYPE TABLE OF ty_bkpf_tc_pago,
      ls_bkpf_tc_pago      TYPE ty_bkpf_tc_pago,
      lt_lifnr             TYPE TABLE OF ty_lifnr,
      ls_lifnr             TYPE ty_lifnr,
      lt_kunnr             TYPE TABLE OF ty_kunnr,
      ls_kunnr             TYPE ty_kunnr,
      lt_lfa1              TYPE ztt_lfa1,
      ls_lfa1              TYPE zst_lfa1,
      lt_kna1              TYPE ztt_kna1,
      ls_kna1              TYPE zst_kna1,
      lt_skb1              TYPE ztt_skb1,
      ls_skb1              TYPE zst_skb1,
      lt_retenciones       TYPE ztt_with_item,
      ls_retenciones       TYPE zst_with_item,
      ls_crp_aa            TYPE zst_zfiglmx_crp_aa.

DATA: lv_tdline            TYPE ztdline,
      lv_vbeln             TYPE vbeln,
      lv_fecha(10)         TYPE c,
      ls_ztasd_fact_uuid   TYPE zst_fact_uuid,
      ls_zvalida_fi        TYPE zst_zvalida_fi,
      ls_t012              TYPE zst_t012,
      ls_bnka              TYPE zst_bnka,
      ls_t012k             TYPE zst_t012k.

DATA: lv_tipo              TYPE koart,
      lv_company           TYPE bukrs,
      lv_doc_number        TYPE belnr_d,
      lv_year              TYPE gjahr,
      lt_doc_rel           TYPE TABLE OF ztt_zcrp_journal_doc_rel,
      ls_doc_rel           TYPE zst_zcrp_journal_doc_rel,
      lv_bktxt_aa          TYPE zst_bkpf-bktxt,
      lv_aa(1)             TYPE c.
