FUNCTION-POOL zvts.                         "MESSAGE-ID ..

TYPES: BEGIN OF ty_ekbe_ent,
         packno LIKE zst_esll-packno,
         introw LIKE zst_esll-introw,
         menge  LIKE zst_esll-menge,
       END   OF ty_ekbe_ent,

       BEGIN OF Ty_PEDIDOS2,
         ebeln             LIKE zekpo-ebeln,
         ebelp             LIKE zekpo-ebelp,
         matnr(8),  " like ekpo-matnr,
*       maktx like makt-maktx,
         txz01             LIKE zekpo-txz01,
         werks             LIKE zekpo-werks,
         menge             LIKE zekpo-menge,
         meins             LIKE zekpo-meins,
*      netpr like ekpo-netpr,
         netpr             TYPE p DECIMALS 3,
         netwr             TYPE p DECIMALS 3,
         peinh             LIKE zekpo-peinh,
         bprme             LIKE zekpo-bprme,
         eindt             TYPE datum,
         uzeit             TYPE uzeit,
         traty             TYPE char4,
         vtext             TYPE char20,
         traid             TYPE char20,
         waers             LIKE zekko-waers,
         verkf             LIKE zekko-verkf,
         ekorg             LIKE zekko-ekorg,
         ernam             LIKE zekko-ernam,
         ekgrp             LIKE zekko-ekgrp,
         bukrs             LIKE zekpo-bukrs,
         knttp             LIKE zekpo-knttp,
         emlif             TYPE lifnr,
         mtart             TYPE mtart,
         banfn             TYPE banfn,
         bnfpo             TYPE bnfpo,
         pstyp             LIKE zekpo-pstyp,
         afnam             TYPE afnam,
         ablad             TYPE ablad,
         wempf             TYPE wempf,
         packno            TYPE packno,
         introw            LIKE zst_esll-introw,
         bstae             TYPE char4,
         matnr2(13),
         atch(1),
         c_atch(1),
         attach1(255), "120
         attach2(255),
         attach3(255),
         attach4(255),
         check(1),
         checkt(1),
         confirmados(1),
         tiene_conf(1),
         tiene_text(1),
         tiene_plan_ent(1),
         plan_ent(1),
         marca(60),
         formula(60),
         direc(1),
         imp(1),
         line(1),
         mwskz             LIKE zekpo-mwskz,
         precio_total      LIKE zekpo-netpr,
         ivas              LIKE zekpo-netpr,
         name1             TYPE name1_a,
         xersy(1),
         xersyt(3),
         serv(1),
         chng(1),
         conf(1),
         texto1(130),
         texto2(130),
         texto3(130),
         cd(1),
         porc(3),
         ent(1),
         matkl             LIKE zekpo-matkl,
         insmk             LIKE zekpo-insmk,
         sakto             TYPE saknr,
         aufnr(25),
         cant_pend         LIKE zekpo-menge,
       END OF Ty_PEDIDOS2,

       BEGIN OF Ty_OFERTA,
         ebeln          LIKE zekpo-ebeln,
         ebelp          LIKE zekpo-ebelp,
         matnr          LIKE zekpo-matnr,
         txz01          LIKE zekpo-txz01,
         ktmng          LIKE zekpo-menge,
         meins          LIKE zekpo-meins,
         netpr          LIKE zekpo-netpr,
         agmem          LIKE zekpo-agmem,
         peinh          LIKE zekpo-peinh,
         bprme          LIKE zekpo-bprme,
         aedat          LIKE zekko-aedat,
         kdatb          LIKE zekko-kdatb,
         kdate          LIKE zekko-kdate,
         angdt          LIKE zekpo-agdat,
         stat(1),
         agtxt          TYPE text30, "tmamt-agtxt,
         dirent         LIKE zst_adrc-name1,
         pstyp          LIKE zekpo-pstyp,
         packno         LIKE zekpo-packno,
         werks          LIKE zekpo-werks,
         eindt          TYPE eindt,
         bednr          LIKE zekpo-bednr,
         idnlf          LIKE zekpo-idnlf,
         plifz(3),  "LIKE EKPO-PLIFZ,
         ekgrp          LIKE zekko-ekgrp,
         bsart          LIKE zekko-bsart,
         eknam          LIKE zst_t024-eknam,
         ektel          LIKE zst_t024-ektel,
         telfx          LIKE zst_t024-telfx,
         mwskz          LIKE zekpo-mwskz,
         txt(1),
         chk(1),
         atch(1),
         c_atch(1),
         attach1(1024),
         attach2(1024),
         attach3(1024),
         attach4(1024),
         attach5(1024),
         attach6(1024),
         attach7(1024),
         attach8(1024),
         attach9(1024),
         attach10(1024),
         xbsart(20),
         lifnr          LIKE zekko-lifnr,
         ernam          LIKE zekko-ernam,
         waers          LIKE zekko-waers,
         wkurs          LIKE zekko-wkurs,
         ihran          LIKE zekko-ihran,
         ihrez          LIKE zekko-ihrez,
         unsez          LIKE zekko-unsez,
         inco1          LIKE zekko-inco1,
         inco2          LIKE zekko-inco2,
         zterm          LIKE zekko-zterm,
         zbd1t          LIKE zekko-zbd1t,
         zbd2t          LIKE zekko-zbd2t,
         zbd3t          LIKE zekko-zbd3t,
         zbd1p          LIKE zekko-zbd1p,
         zbd2p          LIKE zekko-zbd2p,
         adrnr          LIKE zekpo-adrnr,
         banfn          TYPE banfn,
         text1(255),
         text2(255),
         text3(255),
         text4(255),
         text5(255),
         text6(255),
         text7(255),
         text8(255),
         text9(255),
         text10(255),
         text11(255),
         text12(255),
         text13(255),
         text14(255),
         text15(255),
         text16(255),
         text17(255),
         text18(255),
         text19(255),
         text20(255),
         texta1(255),
         texta2(255),
         texta3(255),
         texta4(255),
         texta5(255),
         texta6(255),
         texta7(255),
         texta8(255),
         texta9(255),
         texta10(255),
         texta11(255),
         texta12(255),
         texta13(255),
         texta14(255),
         texta15(255),
         texta16(255),
         texta17(255),
         texta18(255),
         texta19(255),
         texta20(255),
         default(4),
         add(4),
         total(4),
         displ_i(1),
*       J_1BMATUSE like ekpo-J_1BMATUSE, "J_1BINDUST,
*       J_1BNBM    like ekpo-J_1BNBM,
*       J_2BNBM    like ekpo-J_1BNBM,
*       J_1BMATORG like ekpo-J_1BMATORG,
         icms(2),
         ricms(1),
         icmsbr(5),
         sticms(1),
         sti(1),
         mr(1),
         ipi(5),
         comments(2000),
*       comment(8000),
       END OF Ty_OFERTA,

       BEGIN OF Ty_ESLL,
         packno     LIKE zst_ESLL-packno,
         sub_packno LIKE zst_ESLL-sub_packno,
       END OF Ty_ESLL,

       BEGIN OF Ty_ESLL2,
         check(1),
         key            LIKE zst_ESLL-packno,
         packno         LIKE zst_ESLL-packno,
         introw         LIKE zst_ESLL-introw,
         extrow         LIKE zst_ESLL-extrow,
         ktext1         LIKE zst_ESLL-ktext1,
         menge          LIKE zst_ESLL-menge,
         tbtwr          LIKE zst_ESLL-tbtwr,
         meins          LIKE zst_ESLL-meins,
         comments(2000),
       END OF Ty_ESLL2,

       BEGIN OF ty_belnr,
         sign(1),
         option(2),
         low       LIKE zes_ekbe-belnr,
         high      LIKE zes_ekbe-belnr,
         gjahr     LIKE zes_ekbe-gjahr,
       END   OF ty_belnr,

       BEGIN OF ty_ekbe1,
         belnr LIKE zes_ekbe-belnr,
         menge LIKE zes_ekbe-menge,
       END OF ty_ekbe1,

       BEGIN OF ty_tarch3,
         lifnr TYPE lifnr,
         belnr TYPE belnr_d,
         xblnr TYPE xblnr,
         menge LIKE zekpo-menge,
         wrbtr LIKE zst_bsik_payment-wrbtr,
         waers LIKE zst_bsik_payment-waers,
         zfbdt LIKE zst_bsik_payment-zfbdt,
         zbd1t LIKE zst_bsik_payment-zbd1t,
         fecha LIKE sy-datum,
         bldat LIKE zst_bsik_payment-bldat,
         butxt LIKE zes_T001-butxt,
         ebeln LIKE zEKKO-ebeln,
         zuonr LIKE zst_bsik_payment-zuonr,
         sgtxt LIKE zst_bsik_payment-sgtxt,
         textl TYPE text20,
         x     TYPE c,
         zlspr LIKE zst_bsik_payment-zlspr,
       END OF ty_tarch3,

       BEGIN OF ty_tarch4,
         lifnr    TYPE lifnr,
         augbl    TYPE augbl,
         belnr    TYPE belnr_d,
         gjahr    TYPE gjahr,
         buzei(3) TYPE c,
         budat    LIKE sy-datum,
         wrbtr    LIKE zst_bsak_payment-wrbtr,
*        wrbtr(13) type p decimals 2,
         waers(5) TYPE c,
         kursf(9) TYPE c,
         bukrs(4) TYPE c,
         butxt    LIKE zT001-butxt,
         ebeln    LIKE zEKKO-ebeln,
         zuonr    LIKE zst_bsak_payment-zuonr,
         sgtxt    LIKE zst_bsak_payment-sgtxt,
         zlspr    LIKE zst_bsik_payment-zlspr,
         zfbdt    LIKE zst_bsik_payment-zfbdt,
         zbd1t    LIKE zst_bsik_payment-zbd1t,
         xblnr    LIKE zst_bsak_payment-xblnr,
         x        TYPE c,
         bldat    LIKE zst_bsak_payment-bldat,
       END OF ty_tarch4,

       BEGIN OF ty_tarch4_1,
         lifnr     TYPE lifnr,
         augbl     TYPE augbl,
         wrbtr(13) TYPE p DECIMALS 2,
       END OF ty_tarch4_1,

       BEGIN OF ty_c_tarch5,
         lifnr    TYPE lifnr,
         augbl    TYPE augbl,
         budat    TYPE budat,
         belnr    TYPE belnr_d,
         xblnr    TYPE xblnr,
         menge    LIKE zekpo-menge,
         buzei(3) TYPE c,
         wrbtr    LIKE zst_bsak_payment-wrbtr,
         dmbtr    LIKE zst_bsak_payment-dmbtr,
         waers    LIKE zst_bsak_payment-waers,
         kursf(9) TYPE c,
         bukrs(4),
         gjahr(4),
         zuonr    LIKE zst_bsak_payment-zuonr,
         sgtxt    LIKE zst_bsak_payment-sgtxt,
         x        TYPE c,
         bldat    LIKE zst_bsak_payment-bldat,
       END OF ty_c_tarch5,

       BEGIN OF ty_tarch5,
         lifnr    LIKE zst_bsak_payment-lifnr,
         augbl    LIKE zst_bsak_payment-augbl,
         belnr    LIKE zst_bsak_payment-belnr,
         xblnr    LIKE zst_bsak_payment-xblnr,
         menge    LIKE zekpo-menge,
         buzei(3) TYPE c,
         budat    LIKE sy-datum,
         wrbtr    LIKE zst_bsak_payment-wrbtr,
         dmbtr    LIKE zst_bsak_payment-dmbtr,
         waers    LIKE zst_bsak_payment-waers,
         kursf(9) TYPE c,
         ebeln    LIKE zEKKO-ebeln,
         x        TYPE c,
         zuonr    LIKE zst_bseg-zuonr,
         sgtxt    LIKE zst_bseg-sgtxt,
         zlspr    LIKE zst_bsik_payment-zlspr,
         bldat    LIKE zst_bsak_payment-bldat,
       END OF ty_tarch5,

       BEGIN OF ty_error,
         message(255),
       END OF ty_error,

       BEGIN OF Ty_PEDIDOS22,
         ebeln          LIKE zEKPO-ebeln,
         ebelp          LIKE zEKPO-ebelp,
         matnr(18),  " like ekpo-matnr,
         maktx          LIKE zes_MAKT-maktx,
         txz01          LIKE zEKPO-txz01,
         menge          LIKE zEKPO-menge,
         meins          LIKE zEKPO-meins,
*       netpr like ekpo-netpr,
         netpr          TYPE p DECIMALS 3,
         peinh          LIKE zEKPO-peinh,
         bprme          LIKE zEKPO-bprme,
         eindt          TYPE datum,
         uzeit          TYPE uzeit,
         traty          TYPE c LENGTH 4,
         traid          TYPE c LENGTH 20,
         waers          LIKE zEKKO-waers,
         verkf          LIKE zEKKO-verkf,
         ekorg          LIKE zEKKO-ekorg,
         werks          LIKE zEKPO-werks,
         bukrs          LIKE zEKPO-bukrs,
         pstyp          LIKE zekpo-pstyp,
         packno         LIKE zekpo-packno,
         ptext          TYPE c LENGTH 20,
         matnr2(18),
         check(1),
         confirmados(1),
         tiene_conf(1),
         marca(60),
         formula(60),
         porc(3),
         line(1),
         texto1(130),
         texto2(130),
         texto3(130),
         cant_pend      LIKE zst_ekes-menge,
       END OF Ty_PEDIDOS22.

DATA: t_pedidos33 TYPE TABLE OF ty_pedidos22.

DATA: BEGIN OF bdc_str.
        INCLUDE STRUCTURE zst_bdcdata.
DATA: END OF bdc_str.

DATA: BEGIN OF st_textod.
        INCLUDE STRUCTURE zst_tline.
DATA: END OF st_textod.

*---> Confirmación de Pedidos
DATA: t_detail TYPE TABLE OF zvts_po_confirm.

DATA: it_messages TYPE TABLE OF bapiret2,
      it_item     TYPE TABLE OF zst_bapimepoitem,
      it_itemx    TYPE TABLE OF zst_bapimepoitemx.

DATA: theader LIKE zst_thead,
      length  TYPE n,
      ofs     TYPE i,
      ind132  TYPE i.

DATA: t_texto2   TYPE ztt_tline,
      st_texto2  TYPE zst_tline,
      messtab    TYPE STANDARD TABLE OF zst_BDCMSGCOLL,
      st_messtab LIKE LINE OF messtab,
      bdc_tab    TYPE STANDARD TABLE OF zst_bdcdata,
      t_textod   TYPE STANDARD TABLE OF zst_tline.

DATA: disp_mode      VALUE 'N',
      l_mstring(100),
      l_mess(300),
      l_vendor       LIKE zst_lfa1-lifnr,
      flag_err       LIKE sy-tabix.

DATA: t_ekbe_ent  TYPE STANDARD TABLE OF ty_ekbe_ent,
      ls_ekbe_ent LIKE LINE OF t_ekbe_ent,
      t_error     TYPE STANDARD TABLE OF ty_error,
      ls_error    LIKE LINE OF t_error,
      t_ekbe_ped  TYPE STANDARD TABLE OF ty_ekbe_ent,
      ls_ekbe_ped LIKE LINE OF t_ekbe_ped,
      t_oferta    TYPE STANDARD TABLE OF ty_oferta,
      ls_oferta   LIKE LINE OF t_oferta,
      t_esll      TYPE STANDARD TABLE OF ty_esll,
      ls_esll     LIKE LINE OF t_esll,
      t_esll2     TYPE STANDARD TABLE OF ty_esll2,
      ls_esll2    LIKE LINE OF t_esll2,
      p_belnr     TYPE STANDARD TABLE OF ty_belnr,
      ls_belnr    LIKE LINE OF p_belnr,
      t_ekbe1     TYPE STANDARD TABLE OF ty_ekbe1,
      ls_ekbe1    LIKE LINE OF t_ekbe1,
      tarch3      TYPE STANDARD TABLE OF ty_tarch3,
      ls_tarch3   LIKE LINE OF tarch3,
      tarch4      TYPE STANDARD TABLE OF ty_tarch4,
      ls_tarch4   LIKE LINE OF tarch4,
      tarch4_1    TYPE STANDARD TABLE OF ty_tarch4_1,
      ls_tarch4_1 LIKE LINE OF tarch4_1,
      tarch4_2    TYPE HASHED TABLE OF ty_tarch4_1 WITH UNIQUE KEY lifnr augbl,
      ls_tarch4_2 LIKE LINE OF tarch4_2,
      c_tarch5    TYPE STANDARD TABLE OF ty_c_tarch5,
      ls_c_tarch5 LIKE LINE OF c_tarch5,
      tarch5      TYPE STANDARD TABLE OF ty_tarch5,
      ls_tarch5   LIKE LINE OF tarch5.


DATA: t_pedidos   TYPE STANDARD TABLE OF zst_pedidos,
      t_pedidos2  TYPE STANDARD TABLE OF ty_pedidos2,
      ls_pedidos2 LIKE LINE OF t_pedidos2,
      t_pedidos3  TYPE STANDARD TABLE OF ty_pedidos2,
      ls_pedidos3 LIKE LINE OF t_pedidos3,
      t_ekko      TYPE STANDARD TABLE OF zst_pedidos_cab,
      ls_ekko     LIKE LINE OF t_ekko,
      t_ekpo      TYPE STANDARD TABLE OF zst_pedidos2,
      ls_ekpo2    LIKE LINE OF t_ekpo,
      t_eket      TYPE STANDARD TABLE OF zst_eket,
      ls_eket     LIKE LINE OF t_eket,
      t_eban      TYPE STANDARD TABLE OF zst_eban,
      ls_eban     LIKE LINE OF t_eban.

DATA: prov(10),
      provc(10)      TYPE n,
      n_ebeln(10)    TYPE n,
      l_message(255),
      p_lan          TYPE sy-langu,
      date(1),
      l_rec          TYPE sy-tabix,
      p_kursf        LIKE zes_bkpf-kursf,
      idx            LIKE sy-tabix,
      fec1           TYPE budat,
      fec2           TYPE budat,
      fec_ent1       TYPE datum,
      fec_ent2       TYPE budat,
      waers          TYPE zekko-waers.

DATA: v_fecha1         LIKE zekko-aedat,
      text_line(8000),
      text_linea(8000),
      text_line2(8000),
      gtos_asoc(1),
      v_precio(11),
      v_pstyp(1),
      linea_texto(18),
      l_texto(21),
      l_count          TYPE i,
      fecha(10),
      numinset         LIKE zst_zvts_log-numinset,
      v_precio1        TYPE p DECIMALS 2,
      v_precio2(11),
      v_posicion1      LIKE zst_pedidos2-ebelp,
      v_pedido1        LIKE zst_pedidos2-ebeln,
      v_eindt          LIKE zst_eket-eindt,
      v_term(50),
      h_texta1(130),
      h_texta2(130),
      h_texta3(130),
      h_texta4(130),
      h_text1(130),
      h_text2(130),
      h_text3(130),
      h_text4(130),
      h_text5(130),
      h_text6(130),
      h_text7(130),
      h_text8(130),
      h_default(3),
      h_add(3),
      h_total(3),
      header(1),
      item_serv(10)    TYPE n,
      ssouser1(12).

DATA: posicion(19),
      cantidad(18),
      precio(18),
      peinh(18),
      fecha_ent(18),
      h_comments(255).

DATA: c_ent     LIKE zst_pedidos-menge,
      c_sal     LIKE zst_pedidos-menge,
      ped_menge LIKE zst_esll-menge,
      ent_menge LIKE zst_esll-menge,
      l_ebelp   LIKE zekpo-ebelp,
      dif       LIKE zekpo-menge,
      pos       LIKE sy-tabix.

DATA: r_ebeln   TYPE RANGE OF zekko-ebeln,
      ls_ebeln  LIKE LINE OF r_ebeln,
      f_ebeln   TYPE RANGE OF zekko-ebeln,
      r_bukrs   TYPE RANGE OF zekko-bukrs,
      ls_bukrs  LIKE LINE OF r_bukrs,
      r_aedat   TYPE RANGE OF zekko-aedat,
      ls_aedat  LIKE LINE OF r_aedat,
      sbudat    TYPE RANGE OF budat,
      ls_sbudat LIKE LINE OF sbudat,
      sblart    TYPE RANGE OF blart,
      ls_sblart LIKE LINE OF sblart,     " classe de doc.
      pgjahr    TYPE RANGE OF gjahr,
      ls_pgjahr LIKE LINE OF pgjahr.     " Año

DATA: tbsik    TYPE STANDARD TABLE OF zst_bsik_payment,
      ls_bsik  LIKE LINE OF tbsik,
      tbsak    TYPE STANDARD TABLE OF zst_bsak_payment,
      ls_bsak  LIKE LINE OF tbsak,
      tbsak2   TYPE STANDARD TABLE OF zst_bsak_payment,
      ls_bsak2 LIKE LINE OF tbsak2.

DATA: mensaje(255).

DATA: gv_agtxt TYPE text30.

DATA: gt_ekbe TYPE STANDARD TABLE OF zes_ekbe,
      gs_ekbe LIKE LINE OF gt_ekbe,
      gt_essr TYPE STANDARD TABLE OF zst_essr,
      gs_essr LIKE LINE OF gt_essr,
      gt_esll TYPE STANDARD TABLE OF zst_esll,
      gs_esll LIKE LINE OF gt_esll,
      gt_ekko TYPE STANDARD TABLE OF zekko,
      gs_ekko LIKE LINE OF gt_ekko,
      gt_ekes TYPE STANDARD TABLE OF zst_ekes,
      gs_ekes LIKE LINE OF gt_ekes.

DATA: id   LIKE zst_thead-tdid,
      nom  LIKE zst_thead-tdname,
      len  LIKE zst_thead-tdspras,
      len2 LIKE zst_thead-tdspras,
      obj  LIKE zst_thead-tdobject.
